---
name: 🐛 Bug Report
description: Encounter a bug or issue with this project? Report it here, and we'll investigate and resolve it as soon as possible!
labels: ["bug", "P2: moderate"]
assignees:
  - homelab-alpha
body:
  - type: checkboxes
    id: duplicate-check
    attributes:
      label: ⚠️ Please check if this bug has already been reported
      description: |
        To avoid duplicate reports, please search for existing issues before submitting a new one. You can find the list of current issues **[HERE](https://github.com/homelab-alpha/npm-workspaces-template/issues?q=is%3Aissue%20sort%3Acreated-desc%20)**.
      options:
        - label: |
            I have searched the [existing issues](https://github.com/homelab-alpha/npm-workspaces-template/issues?q=is%3Aissue%20sort%3Acreated-desc%20) and found no similar reports.
          required: true

  - type: checkboxes
    id: security-policy-agreement
    attributes:
      label: 🛡️ Security Policy Agreement
      description: |
        Please review and acknowledge the Security Policy before reporting any security-related bugs or issues. You can find the full Security Policy **[HERE](https://github.com/homelab-alpha/npm-workspaces-template/security/policy)**.
      options:
        - label: |
            I have read and agree to Homelab-Alpha's [Security Policy](https://github.com/homelab-alpha/npm-workspaces-template/security/policy).
          required: true

  - type: textarea
    id: bug-description
    validations:
      required: true
    attributes:
      label: 🐛 Bug Description
      description: |
        Provide a detailed explanation of the bug. Include steps to reproduce, expected behavior, and actual behavior.
      placeholder: |
        Describe the bug in detail.

  - type: textarea
    id: steps-to-reproduce
    validations:
      required: true
    attributes:
      label: 🧩 Steps to Reproduce
      description: |
        Provide a step-by-step guide to reproduce the bug. Include specific details to help us replicate the issue.
      placeholder: |
        1. Open the app.
        2. Navigate to the settings page.
        3. Click on the 'Save' button.
        4. Observe the error message.
        5. ...

  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: ✔️ Expected Behavior
      description: |
        Describe what you expected to happen.
      placeholder: |
        What should have happened instead?

  - type: textarea
    id: actual-behavior
    validations:
      required: true
    attributes:
      label: ❌ Actual Behavior
      description: |
        Describe what actually happened.
      placeholder: |
        What happened instead?

  - type: textarea
    id: logs-or-errors
    validations:
      required: false
    attributes:
      label: 📜 Logs or Error Messages
      description: |
        Share any logs or error messages related to your issue, if available.
      render: bash session
      placeholder: |
        Paste logs or error messages here. This will be automatically formatted into code, so no need for backticks.

  - type: textarea
    id: relevant-config-files
    validations:
      required: false
    attributes:
      label: ⚙️ Relevant Configuration Files
      description: |
        Attach any relevant configuration files or code snippets that might help diagnose the issue.
      render: bash session
      placeholder: |
        Paste or upload your configuration files/code snippets here. This will be automatically formatted into code, so no need for backticks.

  - type: input
    id: software-version
    validations:
      required: true
    attributes:
      label: 📦 Software Version
      description: |
        Specify the version of the software you are using. Avoid using vague terms like 'latest' or 'current'.
      placeholder: |
        e.g., 1.10.0

  - type: input
    id: operating-system
    validations:
      required: true
    attributes:
      label: 💻 Operating System
      description: |
        Provide the details of the operating system and architecture you are using.
      placeholder: |
        e.g., Ubuntu Server 24.04.1 LTS (GNU/Linux 6.8.0-48-generic x86_64)

  - type: textarea
    id: environment-setup
    validations:
      required: true
    attributes:
      label: 🖥️ Environment Setup
      description: |
        Provide detailed information about your setup to help us understand your environment better:
          - **Dependencies and Versions**: List all dependencies and their versions used in your setup (e.g., Library X v1.2.3, Library Y v4.5.6).
          - **Hosting Environment**: Are you running this on a local machine, cloud provider (AWS, Azure, etc.), or other platforms?
          - **Runtime Details**: Specify the runtime environment, such as Docker, Kubernetes, Node.js, etc.
          - **Database Configuration**: Mention the type of database (e.g., SQLite, MariaDB, PostgreSQL) and any relevant configurations.
          - **Storage Details**: Describe the file system or storage setup used (e.g., ext4, NTFS, ZFS, NFS).
          - **Additional Context**: Other context that might affect the issue.
      value: |
        - Dependencies and Versions:
        - Hosting Environment:
        - Runtime Details:
        - Database Configuration:
        - Storage Details:
        - Additional Context:
