services:
  app:
    container_name: npm-workspaces-template
    image: ghcr.io/homelab-alpha/npm-workspaces-template:0.1.0
    pull_policy: if_not_present
    ports:
      - "3210:3210"
      - "5173:5173"
    restart: unless-stopped
    healthcheck:
      disable: true
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "2"
    stop_grace_period: 1m
    security_opt:
      - no-new-privileges:true
    labels:
      com.docker.compose.project: "npm Workspaces Template"
      com.npm-workspaces-template.description:
        "A boilerplate for npm Workspaces"
