services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: test
    image: ghcr.io/homelab-alpha/npm-workspaces-template:testing
    container_name: npm-workspaces-template-test
    command: npm run test --workspace=server
