services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: npm-workspaces-template-test
    environment:
      NODE_ENV: test
    volumes:
      - ../client:/app/client
      - ../server:/app/server
      - ../package.json:/app/package.json
      - ../package-lock.json:/app/package-lock.json
      - /app/node_modules
    command: npm run test --workspace=server
