services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: npm-workspaces-template-build
    ports:
      - "3210:3210"
    environment:
      NODE_ENV: production
    volumes:
      - ../client:/app/client
      - ../server:/app/server
      - ../package.json:/app/package.json
      - ../package-lock.json:/app/package-lock.json
      - /app/node_modules
