---
name: "Lint PR title"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest

    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refact
            perf
            test
            chore
            revert
          scopes: |
            [a-z]*
          requireScope: false
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character and uses the imperative mood.
            Please refer to the Commit Message Guidelines:
            https://github.com/homelab-alpha/npm-workspaces-template/blob/main/CODE_STYLE_AND_STANDARDS_GUIDES.md#commit-message-guidelines
          ignoreLabels: |
            bot
            ignore-semantic-pull-request
          headerPattern: '^(?<type>[a-z]+)(?:\((?<scope>[a-z]*)\))?: (?<subject>.*)$'
          headerPatternCorrespondence: type, scope, subject
